name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deploy/requirements.txt

    # Add steps for testing your application if needed
    # - name: Test
    #   run: |
    - name: Zip the deploy repository
      run: zip -r deployment-package.zip ./deploy # Zip only the deploy directory

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "Concentration of Banking"
        environment_name: "ConcentrationofBanking-env"
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deployment-package.zip


